login_app/urls.py
from django.urls import path
from . import views

app_name = 'login_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('request_password_reset/', views.request_password_reset, name='request_password_reset'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('delete_account/', views.delete_account, name='delete_account'),
]

todo_app/urls.py
from django.urls import path
from . import views

app_name = 'todo_app'

urlpatterns = [
    path('todo/', views.index, name='index'),
    path('change_status/', views.change_status, name='change_status'),
    path('completed_todos/', views.completed_todos, name='completed_todos'),
    path('delete_todo/', views.delete_todo, name='delete_todo'),
]

todo_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_app.urls')),
    path('accounts/', include('login_app.urls')),
]

hello/models.py
from django.db import models

# Create your models here.

login_app/models.py
from django.db import models
from django.contrib.auth.models import User
from secrets import token_urlsafe

# Create your models here.

class RequestPasswordReset(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=23, default=token_urlsafe)
    create_timestamp = models.DateTimeField(auto_now_add=True)
    updated_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user} - {self.token}'

todo_app/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    status = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.text} - {self.status}"

hello/views.py
from django.shortcuts import render

# Create your views here.

login_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from .models import RequestPasswordReset
from django.urls import reverse


def login(request):
    context = {}

    if request.method == 'POST':
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user:
            dj_login(request, user)
            return redirect('todo_app:index')
        else:
            context = {
                'error': 'Bad user name or password'
            }
    return render(request, 'login_app/login.html', context)

def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse(request, 'login_app/login.html'))

def sign_up(request):
    context = {}
    if request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        username = request.POST['username']
        email = request.POST['email']
        if password == confirm_password:
            if User.objects.create_user(username, email, password):
                return HttpResponseRedirect(reverse('login_app:login'))
            else:
                context = {
                    'error': 'Could not create account, try again'
                }
        else:
            context = {
                'error': 'Passwords did not match, try again'
            }
    return render(request, 'login_app/sign_up.html', context)

def delete_account(request):
    pass

def request_password_reset(request):
    if request.method == 'POST':
        post_user = request.POST['username']
        user = None

        if post_user:
            try:
                user = User.objects.get(username=post_user)
            except:
                print(f'invalid password request: {post_user}')
        else:
            post_user = request.POST['email']
            try:
                user = User.objects.get(email=post_user)
            except:
                print(f'invalid password request: {post_user}')

        if user:
            prr = RequestPasswordReset()
            prr.user = user
            prr.save()
            print(prr)
            return redirect('login_app:password_reset')
    return render(request, 'login_app/request_password_reset.html')

def password_reset(request):
    if request.method == 'POST':
        post_user = request.POST['username']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        token = request.POST['token']

        if password == confirm_password:
            try:
                prr = RequestPasswordReset().objects.get(token=token)
                prr.save()
            except:
                print('Invalid password reset attempt')
                return render(request, 'login_app/password_reset.html')

            user = prr.user
            user.set_password(password)
            user.save()
            return HttpResponseRedirect(reverse('login_app:login'))

    return render(request, 'login_app/password_reset.html')

todo_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from.models import Todo

def index(request):
    if request.method == 'POST':
        todo = Todo()
        todo.user = request.user
        todo.text = request.POST['text']
        todo.save()

    todos = Todo.objects.filter(user=request.user).filter(status=False)
    context = {
        'todos' : todos
    }
    return render(request, 'todo_app/index.html', context)

def change_status(request):
    pk = request.POST['pk']
    todo = get_object_or_404(Todo, pk=pk)
    if 'checked' in request.POST:
        todo.status = True
    else:
        todo.status = False
    todo.save()
    return HttpResponseRedirect(reverse('todo_app:index'))

def completed_todos(request):
    todos = Todo.objects.filter(status=True)
    return render(request, 'todo_app/completed_todos.html', {'todos' : todos})

def delete_todo(request):
    print(request.META['HTTP_REFERER'])
    if request.method == 'POST':
        pk = request.POST['pk']
        todo = get_object_or_404(Todo, pk=pk)
        todo.delete()
    if request.META['HTTP_REFERER'].split('/')[-2] == 'todo':
        return HttpResponseRedirect(reverse('todo_app:index'))
    else:
        return HttpResponseRedirect(reverse('todo_app:completed_todos'))

login_app/templates/login_app/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <h1>Todo</h1>
        <p>Welcome {{ user }} - <a href="{% url 'login_app:logout' %}">Log out</a> - <a href="{% url 'login_app:delete_account' %}">Delete Account</a></p>
        {% block content %}
        {% endblock %}
        {% block footer %}
        {% endblock %}
    </body>
</html>

login_app/templates/login_app/login.html
{% extends 'todo_app/base.html' %}
{% block content %}
<h1 class="font-bold font-sans text-lg">Login</h1>
        <a class="font-sans text-base colors.emerald" href="{% url 'login_app:sign_up' %}">Sign up</a>
        <hr>
        <form action="{% url 'login_app:login' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="username" placeholder="User Name"/>
            <input type="password" name="password" placeholder="Password"/>
            <button>Login</button>
        </form>
        <hr/>
        {% if error %}
            {{error}}
        {% endif %}
        <a href="{% url 'login_app:request_password_reset' %}">Request Password Reset</a>
    </body>
</html>
{% endblock %}

login_app/templates/login_app/password_reset.html
{% extends 'todo_app/base.html' %}
{% block content %}
<h1>Password Reset</h1>
        <hr>
        <form action="{% url 'login_app:password_reset %}" method="POST">
            {% csrf_token %}
            <input type="text" name="username" placeholder="User Name"/>
            <br>
            <input type="password" name="password" placeholder="Password"/>
            <br>
            <input type="password" name="confirm_password" placeholder="Confirm Password">
            <br>
            <input type="text" name="token" placeholder="Token">
            <br>
            <button>Submit</button>
        </form>
        {% endblock %}

login_app/templates/login_app/request_password_reset.html
{% extends 'todo_app/base.html' %}
{% block content %}
<h1>Request Password Reset</h1>
        <hr>
        <form action="{% url 'login_app:request_password_reset' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="username" placeholder="User Name"/>
            <input type="email" name="email" placeholder="Email"/>
            <button>Submit</button>
        </form>
        <hr/>
        {% endblock %}

login_app/templates/login_app/sign_up.html
{% extends 'todo_app/base.html' %}
{% block content %}
<h1>Sign Up</h1>
        <hr>
        <form action="{% url 'login_app:sign_up' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="username" placeholder="User Name"/>
            <input type="email" name="email" placeholder="Email"/>
            <input type="password" name="password" placeholder="Password"/>
            <input type="password" name="confirm_password" placeholder="Confirm Password"/>
            <button>Sign up</button>
        </form>
        <hr />
        {% if error %}
            {{error}}
        {% endif %}
        {% endblock %}

todo_app/templates/todo_app/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
        <title>Todo</title>
    </head>
    <body>
        <h1 class="font-lg font-bold mb-8">Todo</h1>
        <p class="font-bold mb-4">Welcome {{ user }} - <a class="colors.emerald" href="{% url 'login_app:logout' %}">Log out</a> - <a class="colors.emerald" href="{% url 'login_app:delete_account' %}">Delete Account</a></p>
        {% block content %}
        {% endblock %}
        {% block footer %}
        {% endblock %}
    </body>
</html>

todo_app/templates/todo_app/completed_todos.html
{% extends todo_app/base.html %}
{% block content %}
<h2>Completed todos</h2>

<ul>
    {% for todo in todos %}
            <li>
                <form action="{% url 'todo_app:change_status' %}" method"POST">
                    {% csrf_token %}
                    <input type="hidden" name="pk">
                    <input type="checkbox" name="checked">
                    <button>Update</button>
                    <button formaction="{% url 'todo_app:delete_todo' %}">Delete</button>
                </form>
                {{todo.text}}
            </li>
    {% endfor %}
</ul>
<hr>
{% endblock %}
{% block footer %}
<a href="{% url 'todo_app:index' %}">Back to todos</a>
{% endblock %}

todo_app/templates/todo_app/index.html
{% extends "todo_app/base.html" %}

{% block content %}
    <hr />
    <ul>
    {% for todo in todos  %}
        <li>
            <form action="{% url 'todo_app:change_status' %}" method="POST">
                {% csrf_token %}
                <input type="checkbox" name="checked" {% if todo.status %}checked{% endif %} >
                <button>Update</button>
                <button formaction="{% url 'todo_app:delete_todo' %}">Delete</button>
                <input type="hidden" name="pk" value="{{ todo.pk }}">
                {{ todo.text }}
            </form>
        </li>
        {% endfor %}
    </ul>
    <hr />
    <form action="." method="POST">
        {% csrf_token %}
        <input type="text" name="text" placeholder="Write your todo item here!" />
        <button>Create todo</button>
    </form>
    <hr />
    <a href="{% url 'todo_app:completed_todos' %}">Completed Todos</a>
{% endblock %}